PLUGIN_NAME=		mullvad
PLUGIN_VERSION=		0.1
PLUGIN_DEVEL=       yes
PLUGIN_COMMENT=		mullvad VPN plugin
PLUGIN_DEPENDS=		os-wireguard
PLUGIN_MAINTAINER=	agh1467@protonmail.com

.include "../../Mk/plugins.mk"
